### Use-case: An Online Shopping Mall has provided this dataset.
### Your job is to create a model that can predict whether the customer will shop or not based on customer's age, gender and estimated salary.

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('Social_Network_Ads.csv')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [5]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
data.Purchased.value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [27]:
feature = data.iloc[:, [1,2,3]].values
label = data.iloc[:,4].values

In [29]:
feature[:,0]

array(['Male', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female',
       'Female', 'Male', 'Female', 'Female', 'Female', 'Male', 'Male',
       'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female',
       'Male', 'Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male',
       'Male', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female',
       'Male', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Female', 'Female', 'Female', 'Male',
       'Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female',
       'Male', 'Male', 'Female', 'Female', 'Female', 'Male', 'Female',
       'Female', 'Female', 'Male', 'Male', 'Male', 'Female', 'Female',
       'Female', 'Male', 'Male', 'Male', 'Male', 'Female', 'Female',
       'Male', 'Female', 'Male', 'Male', 'Male', 'Female', 'Male',
       'Female', 'Female', 'Female', 'Female', 'Male', 'Male', 'Female',
  

In [32]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
fgender = ohe.fit_transform(feature[:,0].reshape(-1,1))
fgender

/Users/maryam/miniconda3/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.

In [37]:
feature[:, [1,2]]

array([[19, 19000],
       [35, 20000],
       [26, 43000],
       [27, 57000],
       [19, 76000],
       [27, 58000],
       [27, 84000],
       [32, 150000],
       [25, 33000],
       [35, 65000],
       [26, 80000],
       [26, 52000],
       [20, 86000],
       [32, 18000],
       [18, 82000],
       [29, 80000],
       [47, 25000],
       [45, 26000],
       [46, 28000],
       [48, 29000],
       [45, 22000],
       [47, 49000],
       [48, 41000],
       [45, 22000],
       [46, 23000],
       [47, 20000],
       [49, 28000],
       [47, 30000],
       [29, 43000],
       [31, 18000],
       [31, 74000],
       [27, 137000],
       [21, 16000],
       [28, 44000],
       [27, 90000],
       [35, 27000],
       [33, 28000],
       [30, 49000],
       [26, 72000],
       [27, 31000],
       [27, 17000],
       [33, 51000],
       [35, 108000],
       [30, 15000],
       [28, 84000],
       [23, 20000],
       [25, 79000],
       [27, 54000],
       [30, 135000],
       [31, 8900

In [38]:
finalFeatures = np.concatenate((fgender, feature[:, [1,2]]) , axis = 1)
finalFeatures

array([[0.0, 1.0, 19, 19000],
       [0.0, 1.0, 35, 20000],
       [1.0, 0.0, 26, 43000],
       ...,
       [1.0, 0.0, 50, 20000],
       [0.0, 1.0, 36, 33000],
       [1.0, 0.0, 49, 36000]], dtype=object)

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

for i in range(1,401):
    X_train, X_test, y_train, y_test = train_test_split(finalFeatures, label, test_size=0.2, random_state=i)
    model = LogisticRegression()
    model.fit(X_train,y_train)
    train_score = model.score(X_train,y_train)
    test_score = model.score(X_test,y_test)

    if test_score > train_score:
        print("Test {}, Train {}, RS {}".format(test_score,train_score, i))

Test 0.6875, Train 0.63125, RS 3
Test 0.7375, Train 0.61875, RS 4
Test 0.6625, Train 0.6375, RS 5
Test 0.65, Train 0.640625, RS 6
Test 0.675, Train 0.634375, RS 7
Test 0.675, Train 0.634375, RS 8
Test 0.65, Train 0.640625, RS 10
Test 0.6625, Train 0.6375, RS 11
Test 0.7125, Train 0.625, RS 13
Test 0.675, Train 0.634375, RS 16
Test 0.7, Train 0.628125, RS 17
Test 0.7, Train 0.628125, RS 21
Test 0.65, Train 0.640625, RS 24
Test 0.6625, Train 0.6375, RS 25
Test 0.75, Train 0.615625, RS 26
Test 0.675, Train 0.634375, RS 27
Test 0.7, Train 0.628125, RS 28
Test 0.6875, Train 0.63125, RS 29
Test 0.6875, Train 0.63125, RS 31
Test 0.6625, Train 0.6375, RS 37
Test 0.7, Train 0.628125, RS 39
Test 0.7, Train 0.628125, RS 40
Test 0.65, Train 0.640625, RS 42
Test 0.725, Train 0.621875, RS 46
Test 0.65, Train 0.640625, RS 48
Test 0.675, Train 0.634375, RS 50
Test 0.65, Train 0.640625, RS 51
Test 0.65, Train 0.640625, RS 54
Test 0.7, Train 0.63125, RS 55
Test 0.65, Train 0.640625, RS 56
Test 0.6625, T

In [40]:
X_train, X_test, y_train, y_test = train_test_split(finalFeatures, label, test_size=0.2, random_state=199)
finalModel = LogisticRegression()
finalModel.fit(X_train,y_train)

LogisticRegression()

In [41]:
print(finalModel.score(X_train,y_train))
print(finalModel.score(X_test,y_test))

0.778125
0.8375
